adds help command
gtr/dash pull request #1
Opened 2021-03-20 00:01 UTC by anistarafdar

consider adding an ls command, and maybe add command line arguments to main to run stuff before launching the shell if you want, for example "dash help" runs help

hopefully my addition doesnt break the program, i didnt bother compiling to test but it looked fine to me

ive heard that the best practice for using if statements in C is to "always use the { } braces even when they are not necessary", since it makes changing code around it and even reading it easier, imo

2021-03-20 00:03 UTC, anistarafdar commented
https://github.com/chocolate-doom/chocolate-doom/blob/master/HACKING.md

C coding style guideline that i find helpful

2021-03-20 15:55 UTC, gtr requested changes
looks good! i'd just fix the typo on line 151. thank you.

2021-03-20 15:55 UTC, gtr commented on dash.c
> +            "\nGerardo Torres (github.com/gtr)y"
i think there's a typo extra "y"

2021-03-20 15:58 UTC, gtr commented
thanks for your pull request!

> consider adding an ls command, and maybe add command line arguments to main to run stuff before launching the shell if you want, for example "dash help" runs help

the `ls` command actually already works it's delegated to a child process to run separately using `execvp()` on line 110. the reason why `ls` doesn't appear with `cd` and exit` is because the former are built-in commands into dash which can't be run with `execvp()` using C.

2021-03-21 18:41 UTC, gtr approved these changes

2021-03-21 18:41 UTC, gtr commented
thanks!

2021-03-21 18:41 UTC, merged